<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationTitle>PiPrint</ApplicationTitle>
    <AssemblyName>PiPrint</AssemblyName>
    <RootNamespace>PiPrint.App</RootNamespace>
    <ApplicationIcon>Resources\PiPrint.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\PiPrint.ico" />
    <Resource Include="Resources\PiPrint.png" />
  </ItemGroup>

</Project>
